import numpy as np

a = np.array([1,2,3])
#size of np array
print(a.size)
#itemsize is lenght of array element
b = np.array([1,2,3],dtype=np.int64)
b1 = np.array([1,2,3],dtype=np.int8)
b2 = np.array([1,2,3],dtype=np.complex128)
print(b.itemsize,b1.itemsize,b2.itemsize)



In [5]:
np.array([[1,2,3],[4,5,6]],dtype='float')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
#create np array from tuples
typ = np.array((1,2,3))
type(typ)
typ1 = np.array([1,2,3])
type(typ1)

numpy.ndarray

In [16]:
f = np.zeros((3,4))
print(np.ones((1,2)))
#shape of array
print(np.shape(f))

[[1. 1.]]
(3, 4)


In [17]:
#create 3*3 matrix with full of 6 by complex numbers
np.full((3,3),6,dtype="complex")

array([[6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j]])

In [53]:
x = range(1,5)
[i for i in x]
y = np.arange(1,9)
y
y1 = np.arange(1,9,2)
y1 # from 1..9 gets 1+2 = 3 & 3+2 = 5 so on

[1, 2, 3, 4]

array([1, 2, 3, 4, 5, 6, 7, 8])

array([1, 3, 5, 7])

In [62]:
np.random.random((1,7))
#linspace  - start,stop, how many values between start to stop
np.linspace(1,8,10)

array([[0.68043031, 0.87847645, 0.4207051 , 0.70368145, 0.26464405,
        0.4449804 , 0.85132963]])

array([1.        , 1.77777778, 2.55555556, 3.33333333, 4.11111111,
       4.88888889, 5.66666667, 6.44444444, 7.22222222, 8.        ])

In [87]:
f = np.array([[1,2,3,4],[5,6,7,9]])
f.shape
f.reshape(4,2)
#ravel/flatten - flatten array not change original shape of array
f.ravel()
f
f.flatten()
f

(2, 4)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 9]])

array([1, 2, 3, 4, 5, 6, 7, 9])

array([[1, 2, 3, 4],
       [5, 6, 7, 9]])

array([1, 2, 3, 4, 5, 6, 7, 9])

array([[1, 2, 3, 4],
       [5, 6, 7, 9]])

In [222]:
k = np.array([[1,2,3],[4,5,6]])
k
k.min()
k.max()
k.sum()
k.sum(axis=0)  # axis 0 is column
k.sum(axis=1) # axis 1 is row
print("cumulativ sum")
k.cumsum(axis=1)
np.sqrt(k)
np.std(k)
x = np.array([1,2,3])
y = np.array([4,5,6])
x+y
y-x
x*y
x/y
x.dot(y) #matrix product

array([[1, 2, 3],
       [4, 5, 6]])

1

6

21

array([5, 7, 9])

array([ 6, 15])

cumulativ sum


array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

1.707825127659933

array([5, 7, 9])

array([3, 3, 3])

array([ 4, 10, 18])

array([0.25, 0.4 , 0.5 ])

32

In [173]:
#normal array slicing
g = [1,2,4,3,5,6]
g[1:4]
g[:]
g[:5]
g[2:]
g[-2]
# np array slicing
h = np.array([1,2,3,4,5])
h[1:4]
h[-1]
k = np.array([[1,2,3],[4,5,6],[7,8,9]])
k
k[0:1] # 0th row first column
k[0,1] # 0th row first element
k[1,2]
k[0:2,2]
k[-2,1:]
k[:,0:2] # : bring entire row
k[1:,1:]

[2, 4, 3]

[1, 2, 4, 3, 5, 6]

[1, 2, 4, 3, 5]

[4, 3, 5, 6]

5

array([2, 3, 4])

5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2, 3]])

2

6

array([3, 6])

array([5, 6])

array([[1, 2],
       [4, 5],
       [7, 8]])

array([[5, 6],
       [8, 9]])

In [274]:
for i in k:
    for v in i:
        v
#flat flatning array to iterate
for i in k.flat:
    i

a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
'### a ###'
a
'### b ###'
b
np.hstack((a,b))
np.vstack((b,a))

c = np.arange(16).reshape(2,8)
c
np.hsplit(c,4)
np.vsplit(c,2)

'### iterate with nditer ###'
d = np.arange(12).reshape(3,4)
for x in np.nditer(d,order="C"):
    print(x)
'### rewrite array with squre ###'
for x in np.nditer(d,op_flags=['readwrite']):
   x[...]=x*x
d
'### iterate 2 array ###'
e = np.arange(1,10,3).reshape(3,1)
for x,y in np.nditer([d,e]):
    print(x,y)

a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])
for x,y in np.nditer([a1,a2]):
    print(x,y)

1

2

3

4

5

6

1

2

3

4

5

6

'### a ###'

array([[0, 1],
       [2, 3],
       [4, 5]])

'### b ###'

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

array([[ 6,  7],
       [ 8,  9],
       [10, 11],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

[array([[0, 1],
        [8, 9]]),
 array([[ 2,  3],
        [10, 11]]),
 array([[ 4,  5],
        [12, 13]]),
 array([[ 6,  7],
        [14, 15]])]

[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15]])]

'### iterate with nditer ###'

0
1
2
3
4
5
6
7
8
9
10
11


'### rewrite array with squre ###'

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

'### iterate 2 array ###'

0 1
1 1
4 1
9 1
16 4
25 4
36 4
49 4
64 7
81 7
100 7
121 7
1 5
2 6
3 7
4 8


In [218]:
q = np.arange(12).reshape(3,4)
w=q>5 # in qth array compare value greater than 5 if true replace with boolean value
w
q[w] #  bring true array values
q[w] = -1 #Replace true value with custom value
q

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

array([ 6,  7,  8,  9, 10, 11])

array([[ 0,  1,  2,  3],
       [ 4,  5, -1, -1],
       [-1, -1, -1, -1]])

In [248]:
a = np.array([[2,3,4],[20,6,9],[10,27,3]])
np.sort(a)
'### row wise sorting ###'
np.sort(a,axis=1)
'### column wise sorting ###'
np.sort(a,axis=0)
'### sorting structure array###'
header_type = [('Name','S10'),('YOB',int),('marks',float)]
values = [('Janani',1998,95.2),('Sivamani',1990,72.3),('Karthik',1989,80.1),('Loke',1995,90)]
db = np.array(values,dtype=header_type)
np.sort(db,order='marks')
'### sort with 2 values ###'
np.sort(db,order=['marks','YOB'])

array([[ 2,  3,  4],
       [ 6,  9, 20],
       [ 3, 10, 27]])

'### row wise sorting ###'

array([[ 2,  3,  4],
       [ 6,  9, 20],
       [ 3, 10, 27]])

'### column wise sorting ###'

array([[ 2,  3,  3],
       [10,  6,  4],
       [20, 27,  9]])

'### sorting structure array###'

array([(b'Sivamani', 1990, 72.3), (b'Karthik', 1989, 80.1),
       (b'Loke', 1995, 90. ), (b'Janani', 1998, 95.2)],
      dtype=[('Name', 'S10'), ('YOB', '<i4'), ('marks', '<f8')])

'### sort with 2 values ###'

array([(b'Sivamani', 1990, 72.3), (b'Karthik', 1989, 80.1),
       (b'Loke', 1995, 90. ), (b'Janani', 1998, 95.2)],
      dtype=[('Name', 'S10'), ('YOB', '<i4'), ('marks', '<f8')])